### ISSUE TITLE
Error when using setup({...})

### ISSUE THREAD

**Issue by andis-sprinkis** [haringsrob/nvim_context_vt#59] opened 2022-04-17 12:31 UTC
I'm using packer.nvim as package manager and in
```
require('packer').startup(function(use)
  use {
...
```
call setup() from respective plugin `config` parameter
```
...
    {
      'haringsrob/nvim_context_vt',
      config = function ()
        require("nvim_context_vt").setup({
          prefix = ' In:',
        })
      end
    },
...
```

That results in nvim startup error:
![p6R8uk3nj9](https://user-images.githubusercontent.com/52537705/163714243-ecc54f88-baf7-466e-95c1-fc34fef052b6.png)

Plugin works fine when I don't call setup().

OS: Arch Linux
```
$ nvim --version                                                                                                                                     15:30:46
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by andersevenrud** [comment] 2022-04-17 13:04
I tried to reproduce this by copy-pasting the above, but without any success :thinking: 

Could you maybe try to create a minimal working config where this issue occurs and share it ?

**Comment by andis-sprinkis** [comment] 2022-04-17 13:24
OK, it stopped occurring after I removed and reinstalled [impatient.nvim](https://github.com/lewis6991/impatient.nvim/) plugin and now setup() works, so there could have been some module caching issue related to that plugin which I'm not sure I'll be able to replicate. Will keep an eye on it.

**Comment by andersevenrud** [comment] 2022-04-17 13:26
Ah! I've seen similar issues using impatient with other plugins that I maintain and never really found a way to solve it outside doing exactly what you did here.

Glad to hear it works now. Feel free to re-open this issue if you still have issues and I'll try to open a dialogue with the impatient maintainer.

**Comment by andis-sprinkis** [comment] 2022-04-18 16:01
I updated plugins and got same issue, even after removing impatient.nvim, .local/share/nvim, packer /plugins and reinstalling all plugins from scratch, so I think it's something else than impatient.nvim
![pZm6RvlecA](https://user-images.githubusercontent.com/52537705/163835828-ed12ef18-127c-44d7-8969-62101ed0973d.png)
![tbRchLrCgJ](https://user-images.githubusercontent.com/52537705/163835831-6b103d3c-3591-4337-a931-d004c7b1b8a4.png)

I will try to do a minimal config example when I have time in upcoming days.

**Comment by andis-sprinkis** [comment] 2022-04-21 15:33
Stopped occuring when I updated nvim from 0.6.1 to recently released 0.7.0, so probably backwards compat. issue in one of the other treesitter plugins.

**Comment by andis-sprinkis** [comment] 2022-05-15 11:04
Happened today again on nvim startup after I installed my nvim config on a new Arch Linux host with nvim **0.7.0** (cloning config repo into .config/nvim and letting packer bootstrap routine and `PackerSync` run) .
After running `PackerCompile` and `LuaCacheClear` a couple times the error stopped from occurring on nvim startup.

**Comment by andersevenrud** [comment] 2023-07-06 17:05
Closing this since there has been no new reports 🤞

**Closed as completed by andersevenrud** 2023-07-06 17:05 UTC
